FROM nvidia/cuda:11.0-cudnn8-devel-ubuntu18.04

RUN apt update \
    && apt upgrade -y \
    && DEBIAN_FRONTEND="noninteractive" apt install -y tmux htop wget gdb unzip

RUN apt update && apt install -y sox libsox-dev libsox-fmt-all

RUN mkdir /matlab && \
    wget https://ssd.mathworks.com/supportfiles/downloads/R2019a/Release/6/deployment_files/installer/complete/glnxa64/MATLAB_Runtime_R2019a_Update_6_glnxa64.zip -O /matlab/matlab_runtime.zip && \
    apt update && apt install -y libxrender1 libxt6 libxcomposite1 && \
    unzip /matlab/matlab_runtime.zip -d /matlab/matlab_runtime && \
    /matlab/matlab_runtime/install -mode silent -agreeToLicense yes && \
    rm -rf /matlab/matlab_runtime*
ADD hearing_thresholds/_compiled /matlab/hearing_thresholds

COPY requirements.txt /root/asr-python/requirements.txt
RUN apt-get update && apt install -y python3-pip \
    && pip3 install -r /root/asr-python/requirements.txt

RUN pip3 install torch==1.9.1+cu111 torchvision==0.10.1+cu111 torchaudio==0.9.1 -f https://download.pytorch.org/whl/torch_stable.html

# fix montreal forced aligner issue
RUN apt install -y libgfortran3:amd64

RUN apt install -y libxext6

RUN pip3 install python-Levenshtein